### ISSUE TITLE
Hacktoberfest 2021

### ISSUE THREAD

**Issue by Lucs1590** [mauriciomutte/track-correios#2]
Olá @mauriciomutte!
Encontrei esse projeto pelo linkedin e vi que além de já conhece o Hacktoberfest, inclusive, já escreveu sobre esse evento.

Eu olhei seu projeto e gostei demais, então gostaria de saber se você pretende colocá-lo dentro desse evento e se posso fazer um PR para colaborar com o mesmo.

Desde já, muito obrigado! ;)

**Comment by mauriciomutte** [comment]
Seria muito legal mas me cadastrei lá como participante e não mantenedor, não sei se rola 😞

**Comment by Lucs1590** [comment]
Da ultima vez eu fiz assim também e deu certo! 😄 
Se eu fizer um PR com uma atualização, podemos tentar colocar dentro das regras lá?

**Comment by mauriciomutte** [comment]
Claro mano

**Comment by gabrielferreiraa** [comment]
Seria animaaaaaaaaaaal @mauriciomutte

**Comment by Lucs1590** [comment]
Inclusive, consegui ver que é possível mudar a sua configuração e colocar como _mantainer_ ao clicar em "Edit Profile".

![image](https://user-images.githubusercontent.com/38580547/135900714-33ef9ffb-f319-4696-a8f7-9d600eac8225.png)

**Comment by mauriciomutte** [comment]
@Lucs1590 funcionou sua PR?

**Comment by Lucs1590** [comment]
Tudo indica que deu certo sim, @mauriciomutte , veja:
![image](https://user-images.githubusercontent.com/38580547/135934078-9fa3715d-6b8e-4aac-aa54-7e2ff8e2e44e.png)

Muito obrigado pela oportunidade de contribuir com a comunidade! 🎉

**Comment by Nogueira-lucas** [comment]
olá, também estou interessado em contribuir como participante. Achei o projeto legal e está dentro da minha linha de conhecimentos técnicos.
