### ISSUE TITLE
🐛 Invalid Captcha

### ISSUE THREAD

**Issue by davioliveira-dev** [mauriciomutte/track-correios#22]
After having used you a few times, the invalid captcha message appeared, I suspect that my IP/User - Agent used to fetch the data was blocked.

![image](https://user-images.githubusercontent.com/53924113/137917630-2cac2339-b39f-4461-a7d9-f02dee487443.png)

**Comment by cristovaoolegario** [comment]
Opa, tem a API do APP Correios que dá pra usar `https://proxyapp.correios.com.br/v1/sro-rastro/[code]`, tem umas diferenças com a API anterior que vcs tavam usando mas acho que dá pra adaptar hein 😄

**Comment by NicolasPereira** [comment]
Sensacional!
Vou tentar essa semana fazer a adaptação e abrir um PR!
Não sei muito bem TS mas da pra me virar hahaha
